import mongoose from 'mongoose';
import crypto from 'crypto';

function normalizeText(value) {
  return String(value || '')
    .replace(/\s+/g, ' ')
    .trim();
}

function buildSemanticText(data = {}) {
  return [
    `Title: ${normalizeText(data.title)}`,
    `Company: ${normalizeText(data.company)}`,
    `Location: ${normalizeText(data.location)}`,
    `Country: ${normalizeText(data.country)}`,
    `Industry: ${normalizeText(data.industry)}`,
    `Skills: ${(data.skillsExtracted || [])
      .map(normalizeText)
      .filter(Boolean)
      .join(', ')}`,
    `Description: ${normalizeText(data.description)}`
  ].join('\n');
}

function hashSemanticData(data = {}) {
  return crypto
    .createHash('sha256')
    .update(buildSemanticText(data))
    .digest('hex');
}

const jobSchema = new mongoose.Schema(
  {
    source: {
      type: String,
      default: 'jobo'
    },

    externalId: {
      type: String,
      required: true
    },

    title: {
      type: String,
      required: true
    },

    company: String,

    location: String,

    country: String,

    industry: String,

    description: String,

    applyLink: {
      type: String,
      required: true
    },

    skillsExtracted: [String],

    // --------------------------------------------------
    // SEMANTIC MATCHING
    // --------------------------------------------------

    // Vector generated by OpenAI.
    embedding: {
      type: [Number],
      default: undefined
    },

    // Hash of the CURRENT job content.
    embeddingSourceHash: {
      type: String,
      default: null
    },

    // Hash of the content used to create the saved vector.
    //
    // If embeddingHash !== embeddingSourceHash,
    // the embedding needs to be regenerated.
    embeddingHash: {
      type: String,
      default: null
    },

    embeddingUpdatedAt: Date,

    status: {
      type: String,
      enum: ['open', 'closed'],
      default: 'open'
    },

    rawData: mongoose.Schema.Types.Mixed
  },
  {
    timestamps: true
  }
);


// --------------------------------------------------
// AUTOMATIC CHANGE DETECTION
// --------------------------------------------------
//
// All your job APIs currently save jobs using:
//
// Job.findOneAndUpdate(...)
//
// This middleware detects whether searchable job information
// changed.
//
// IMPORTANT:
// It does NOT call OpenAI.
//
// It only creates a very cheap SHA-256 hash.
//
// The embedding worker later sees:
//
// embeddingSourceHash !== embeddingHash
//
// and knows that this job needs a new embedding.
// --------------------------------------------------

jobSchema.pre('findOneAndUpdate', function (next) {
  const update = this.getUpdate() || {};

  const data = update.$set
    ? {
        ...update,
        ...update.$set
      }
    : update;

  const semanticFields = [
    'title',
    'company',
    'location',
    'country',
    'industry',
    'description',
    'skillsExtracted'
  ];

  const hasSemanticContent = semanticFields.some((field) =>
    Object.prototype.hasOwnProperty.call(data, field)
  );

  if (hasSemanticContent) {
    const hash = hashSemanticData(data);

    if (update.$set) {
      update.$set.embeddingSourceHash = hash;
    } else {
      update.embeddingSourceHash = hash;
    }

    this.setUpdate(update);
  }

  next();
});


// --------------------------------------------------
// INDEXES
// --------------------------------------------------

jobSchema.index(
  {
    source: 1,
    externalId: 1
  },
  {
    unique: true
  }
);


// Existing jobs page keyword search.
jobSchema.index({
  title: 'text',
  company: 'text',
  description: 'text'
});


// Helps fallback skill matching.
jobSchema.index({
  status: 1,
  skillsExtracted: 1
});


// Helps locate jobs that need embeddings.
jobSchema.index({
  status: 1,
  embeddingHash: 1,
  embeddingSourceHash: 1
});


export default mongoose.model(
  'Job',
  jobSchema
);
